declare module "tree-sitter-javascript"
declare module "tree-sitter-typescript"
declare module "tree-sitter-python"
declare module "tree-sitter-rust"
declare module "tree-sitter-java"
declare module "tree-sitter-go"
